export const ActionTypes = {
   SET_PRODUCTS: 'SET_PRODUCTS',
   SELECTED_PRODUCT: "SELECTED_PRODUCT",
   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
   IZBRISI_PRODUCT: "IZBRISI_PRODUCT",

   //Check
   DODADI_PRODUCT: "DODADI_PRODUCT",
   ADD_TO_CART: 'ADD_TO_CART',
   ADJUST_QTY: "ADJUST_QTY",
   REMOVE_FROM_CART: 'REMOVE_FROM_CART',

   //Check
   ADD_TO_CART_FROM_DETAILS_PAGE: 'ADD_TO_CART_FROM_DETAILS_PAGE',


   //added after thunk imported
   FETCH_PRODUCTS: "FETCH_PRODUCTS",
   FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",
}